title: Nikhil Tumbde
logo: rel path to image
description: Data Scientist at Mastercard, AI Garage
show_downloads: False
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
